### ISSUE TITLE
Resources documentation

### ISSUE THREAD

**Issue by jgato** [openshift/lvm-operator#102]
Hi there,

would it be possible to have a short documentation about the different resources managed by the operator? In the installation document we can check the LVMCluster Resource, that it is easy to understand how to use and what it does. But, would it be possible to know a little about LogicalVolumes, LVMVolumeGroupNodeStatus, etc?

many thanks,

**Comment by leelavg** [comment]
@jgato 

- PRs are yet to be merged, in the meantime you can refer #99, #100 and #101

**Comment by suleymanakbas91** [comment]
I believe [this PR](https://github.com/openshift/lvm-operator/pull/334) will provide some clarifications.
