### ISSUE TITLE
Use PSPs/Pod security standards to restrict unwanted resource/namespace access to host

### ISSUE THREAD

**Issue by leelavg** [openshift/lvm-operator#29]
- With SCC we can only target namespace level isolation and SELinux, Syscalls filteration
- Add PSP to further restrict this access, for example restricting access to a single directory when using hostPath

**Comment by Madhu-1** [comment]
@leelavg PSP is deprecated in kubernetes 1.21 we should not use it anyone and look for the alternative like pod security https://kubernetes.io/docs/concepts/security/pod-security-standards ?

**Comment by leelavg** [comment]
> PSP is deprecated in kubernetes 1.21 we should not use it anyon
- ack, we are aware of this and so didn't enforce PSPs, as there was no alternative mentioned in PSP blog post (or atleast I missed to notice) this issue is a placeholder wrt security

> alternative like pod security https://kubernetes.io/docs/concepts/security/pod-security-standards ?
- thanks, will look into.

**Comment by suleymanakbas91** [comment]
We will track this at https://issues.redhat.com/browse/OCPVE-344. Thanks @leelavg!
