### ISSUE TITLE
After operator upgrade PVC can not bee processed due to provisioner change

### ISSUE THREAD

**Issue by eugenpro** [openshift/lvm-operator#294]
I've upgraded operator with make deploy command. Old storage class had provisioner topolvm.cybozu.com, now it's topolvm.io, but it didn't updated in my current sc. Now when all pods restarted they can't mount pvc with an error "topolvm.cybozu.com". Now all pv can't be resolved with an error  `kubernetes.io/csi: mounter.SetUpAt failed to get CSI client: driver name topolvm.cybozu.com not found in the list of registered CSI drivers`. How can I correctly upgrade sc and is it possible to upgrade current pvc without loosing data and how avoid such unexpected bugs in future

**Comment by nbalacha** [comment]
@eugenpro , apologies - the documentation has not been updated with the instructions for this breaking change.
The steps to migrate are available in https://github.com/topolvm/topolvm/blob/main/docs/proposals/rename-group.md.

Please let me know if you have any questions.
