### ISSUE TITLE
Feature request : arm64 Image

### ISSUE THREAD

**Issue by fjcloud** [openshift/lvm-operator#335]
Hello! 

I didn't see this operator available on Openshift on ARM. It is planned ?

Thanks!

**Comment by suleymanakbas91** [comment]
Hi @fjcloud,

We already have the images for arm64: https://catalog.redhat.com/software/containers/lvms4/lvms-rhel8-operator/63972de2adcb55263891b97e?architecture=arm64 

Hope it helps!

**Comment by suleymanakbas91** [comment]
We realized that the operator is missing the necessary label for OpenShift on ARM. We will tackle this at https://issues.redhat.com/browse/OCPBUGS-13364. Thanks for pointing this out @fjcloud!

**Comment by suleymanakbas91** [comment]
There was a problem with the metadata. The fix will be released tomorrow and then you should be able to see it on the catalog.

**Comment by fjcloud** [comment]
Just tested it and works perfectly! Thanks
FYI it's with this repo https://github.com/fjcloud/snocp
