### ISSUE TITLE
[VgManager] NodePlugin daemon set fails while waiting for volume groups to be created

### ISSUE THREAD

**Issue by sp98** [openshift/lvm-operator#41]
VgManager is waiting for sometime before creating vgs.  Lvmd containers  in the node plugins fails until the VG is created.
Need to check if vgManager should really wait before creating devices.

**Comment by suleymanakbas91** [comment]
Improved in https://github.com/openshift/lvm-operator/commit/fc8b3b8ac627cba0e51da3a09abfe526cbe70037.
