### ISSUE TITLE
Q: How to change the `reclaimPolicy` of the storage class created by `LVMCluster`

### ISSUE THREAD

**Issue by anjannath** [openshift/lvm-operator#593]
trying out the operator on a local CRC cluster, everything is working nicely and as expected, but I'd like to have the `reclaimPolicy: Retain` instead of `Delete`, i have the following `LVMCluster` definition and the `StorageClass` it created, how can we set the reclaimPolicy for the storage class in the `LVMCluster` definition?

```yaml
apiVersion: lvm.topolvm.io/v1alpha1
kind: LVMCluster
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"lvm.topolvm.io/v1alpha1","kind":"LVMCluster","metadata":{"annotations":{},"name":"crc-topolvm-cluster","namespace":"openshift-storage"},"spec":{"storage":{"deviceClasses":[{"default":true,"deviceSelector":{"forceWipeDevicesAndDestroyAllData":true,"paths":["/dev/vdb"]},"name":"lvm-storage-topolvm","thinPoolConfig":{"name":"thin-pool-1","overprovisionRatio":10,"sizePercent":90}}]},"tolerations":null}}
  creationTimestamp: "2024-03-20T07:02:26Z"
  finalizers:
  - lvmcluster.topolvm.io
  generation: 1
  name: crc-topolvm-cluster
  namespace: openshift-storage
  resourceVersion: "31392"
  uid: 73b3613a-9035-47a3-8d7b-5685274a4b73
spec:
  storage:
    deviceClasses:
    - default: true
      deviceSelector:
        paths:
        - /dev/vdb
      fstype: xfs
      name: lvm-storage-topolvm
      thinPoolConfig:
        name: thin-pool-1
        overprovisionRatio: 10
        sizePercent: 90
status:
  deviceClassStatuses:
  - name: lvm-storage-topolvm
    nodeStatus:
    - devices:
      - /dev/vdb
      node: crc-b56wv-master-0
      status: Ready
  ready: true
  state: Ready
```

```yaml
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    description: Provides RWO and RWOP Filesystem & Block volumes
  creationTimestamp: "2024-03-20T07:02:27Z"
  name: lvms-lvm-storage-topolvm
  resourceVersion: "31011"
  uid: 3ed47b6f-3f78-44fe-adf2-9a264ce7be81
parameters:
  csi.storage.k8s.io/fstype: xfs
  topolvm.io/device-class: lvm-storage-topolvm
provisioner: topolvm.io
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
```

**Comment by jakobmoellerdev** [comment]
For now, create the LVMCluster and wait for the storageClass creation, after that edit the storage class to have reclaimPolicy Retain.

For more information on why we dont support switching this, see https://github.com/topolvm/topolvm/blob/93059ac6dd8e17b2215bf94ea7789b5d74558583/docs/limitations.md?plain=1#L14-L22

**Comment by jakobmoellerdev** [comment]
Let me know why you need Retain and maybe I can help you somehow get what you need :)

**Comment by anjannath** [comment]
> For more information on why we dont support switching this, see https://github.com/topolvm/topolvm/blob/93059ac6dd8e17b2215bf94ea7789b5d74558583/docs/limitations.md?plain=1#L14-L22

thanks, this helps!

> Let me know why you need Retain and maybe I can help you somehow get what you need :)

this was requirement from one of the user's of OpenShift Local (CRC), the user wanted to keep the PV data around for later even after removing the claim

but from what i understand is in LVMS the lvm pv will not be deleted when pvc is deleted but the k8s pv object is deleted, is that correct? so the user could still get the data back from the volume after deleting the claim

**Comment by jakobmoellerdev** [comment]
> but from what i understand is in LVMS the lvm pv will not be deleted when pvc is deleted but the k8s pv object is deleted, is that correct? 

Yeah that sounds right to me. The data will only be kept on Retain which can be set atomatically for each PersistentVolume that is created, even if the StorageClass is set to Delete. I will say that during the unmount, the device mount path gets removed however, so the user will have to manually remount the volume before accessing the data. Either way, the volume can not be reused for another PVC due to the dynamic provisioning nature, so a migration would have to be done manually.

**Comment by jakobmoellerdev** [comment]
Closing this as I am assuming there is no further need to discuss.
