### ISSUE TITLE
topolvm container getting OOM killed

### ISSUE THREAD

**Issue by nbalacha** [openshift/lvm-operator#67]
From the topolvm -node pod:

  - containerID: cri-o://ad1270fd321439c82dfad3a0775065e15cc3ce96ce3d085dc94c66c5a2138302
    image: quay.io/topolvm/topolvm:0.10.3
    imageID: quay.io/topolvm/topolvm@sha256:4fbbac323f1cc2310d717efa76b9205f1a79d360291be2efd08eb2d1f6971ca2
    lastState:
      terminated:
        containerID: cri-o://ea27712cbf16533dff038f2a1871f24868f4a3bab6d264342c1e4c25c1e57b34
        exitCode: 137
        finishedAt: "2022-01-10T13:10:53Z"
        reason: OOMKilled
        startedAt: "2022-01-10T13:10:36Z"

**Comment by suleymanakbas91** [comment]
Will close this. We can re-open if we encounter this problem again.
