### ISSUE TITLE
Check infra features in CSV

### ISSUE THREAD

**Issue by mulbc** [openshift/lvm-operator#85]
It is important that we verify that our CSVs are labeled correctly for when we appear in OperatorHub.

See this link for labels:
https://docs.openshift.com/container-platform/4.9/operators/operator_sdk/osdk-generating-csvs.html#osdk-csv-manual-annotations_osdk-generating-csvs

IMO we should make sure `operators.openshift.io/infrastructure-features` is set to `csi` and maybe also to `fips` (once we test it)

**Comment by suleymanakbas91** [comment]
Added in https://github.com/openshift/lvm-operator/pull/338.
